### ISSUE TITLE
include event recorders in controller to add events to environment object

### ISSUE THREAD

**Issue by rajendragosavi** [rajendragosavi/my-experimental-operator#11]
sample code in loadbalancer provisioning

```Go 
func (c *Controller) processServiceCreateOrUpdate(ctx context.Context, service *v1.Service, key string) error {
	// TODO(@MrHohn): Remove the cache once we get rid of the non-finalizer deletion
	// path. Ref https://github.com/kubernetes/enhancements/issues/980.
	cachedService := c.cache.getOrCreate(key)
	if cachedService.state != nil && cachedService.state.UID != service.UID {
		// This happens only when a service is deleted and re-created
		// in a short period, which is only possible when it doesn't
		// contain finalizer.
		if err := c.processLoadBalancerDelete(ctx, cachedService.state, key); err != nil {
			return err
		}
	}
	// Always cache the service, we need the info for service deletion in case
	// when load balancer cleanup is not handled via finalizer.
	cachedService.state = service
	op, err := c.syncLoadBalancerIfNeeded(ctx, service, key)
	if err != nil {
		c.eventRecorder.Eventf(service, v1.EventTypeWarning, "SyncLoadBalancerFailed", "Error syncing load balancer: %v", err)
		return err
	}
	if op == deleteLoadBalancer {
		// Only delete the cache upon successful load balancer deletion.
		c.cache.delete(key)
	}

	return nil
}
```
sample event recorded

```yaml

╰─ k describe svc lb-service
Name:                     lb-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=demo-app
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.21.31.78
IPs:                      10.21.31.78
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30448/TCP
Endpoints:                10.20.72.2:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Normal   EnsuringLoadBalancer    14s (x3 over 31s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  14s (x3 over 29s)  service-controller  Error syncing load balancer: failed to ensure load balancer: error getting address for node pooler-1724760593: no address found for host
```
